// mobile/src/components/ui/generic-text.tsx
import React, { useMemo, useState } from 'react';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';

type TokenType = 'text' | 'mention' | 'hashtag' | 'link' | 'emoji' | 'bold' | 'italic' | 'highlight';

type ParsedToken = {
    type: TokenType;
    value: string;
};

type GenericTextProps = {
    text?: string;
    maxCharacters?: number;
    expandable?: boolean;
    theme?: 'light' | 'dark';
    textColor?: string;
    clickableMentions?: boolean;
    clickableHashtags?: boolean;
    clickableLinks?: boolean;
    highlightTerms?: string[];
    translatedText?: string;
    enableMarkdown?: boolean;
    analyticsId?: string;
    fontSize?: number;
    onMentionPress?: (username: string) => void;
    onHashtagPress?: (hashtag: string) => void;
    onLinkPress?: (url: string) => void;
};

const tokenRegex = /(https?:\/\/[^\s]+)|(@[\p{L}0-9_.]+)|(#[\p{L}0-9_]+)|(\*\*.*?\*\*)|(\*.*?\*)|([\u{1F300}-\u{1FAFF}])/gu;

const GenericText = ({
    text = '',
    maxCharacters = 180,
    expandable = true,
    theme = 'light',
    textColor = 'none',
    clickableMentions = true,
    clickableHashtags = true,
    clickableLinks = true,
    highlightTerms = [],
    translatedText,
    enableMarkdown = true,
    analyticsId,
    fontSize = 14,
    onMentionPress,
    onHashtagPress,
    onLinkPress
}: GenericTextProps) => {
    const [expanded, setExpanded] = useState(false);

    const currentText = translatedText || text || '';
    const isLongText = currentText.length > maxCharacters;

    const displayedText = !expandable || expanded || !isLongText
        ? currentText
        : `${currentText.slice(0, maxCharacters)}...`;

    const baseColor = textColor && textColor !== 'none'
        ? textColor
        : theme === 'dark'
            ? '#ffffff'
            : '#111111';

    const tokens = useMemo(() => parseText(displayedText, highlightTerms, enableMarkdown), [displayedText, highlightTerms, enableMarkdown]);

    const handleMentionPress = (username: string) => {

        if (onMentionPress) {
            onMentionPress(username);
            return;
        }

        router.push(`profile/${username}` as never);
    };

    const handleHashtagPress = (hashtag: string) => {
        if (onHashtagPress) {
            onHashtagPress(hashtag);
            return;
        }

        router.push(`/explore/topics/${hashtag}` as never);
    };

    const handleLinkPress = async (url: string) => {

        if (onLinkPress) {
            onLinkPress(url);
            return;
        }

        const canOpen = await Linking.canOpenURL(url);

        if (canOpen) {
            await Linking.openURL(url);
        }
    };

    const renderToken = (token: ParsedToken, index: number) => {
        if (token.type === 'mention') {
            return (
                <Text
                    key={`${token.type}-${token.value}-${index}`}
                    style={[styles.clickableText, { fontSize }]}
                    onPress={() => clickableMentions && handleMentionPress(token.value)}
                >
                    @{token.value}
                </Text>
            );
        }

        if (token.type === 'hashtag') {
            return (
                <Text
                    key={`${token.type}-${token.value}-${index}`}
                    style={[styles.clickableText, { fontSize }]}
                    onPress={() => clickableHashtags && handleHashtagPress(token.value)}
                >
                    #{token.value}
                </Text>
            );
        }

        if (token.type === 'link') {
            return (
                <Text
                    key={`${token.type}-${token.value}-${index}`}
                    style={[styles.linkText, { fontSize }]}
                    onPress={() => clickableLinks && handleLinkPress(token.value)}
                >
                    {token.value}
                </Text>
            );
        }

        if (token.type === 'bold') {
            return (
                <Text key={`${token.type}-${token.value}-${index}`} style={[styles.boldText, { color: baseColor, fontSize }]}> 
                    {token.value}
                </Text>
            );
        }

        if (token.type === 'italic') {
            return (
                <Text key={`${token.type}-${token.value}-${index}`} style={[styles.italicText, { color: baseColor, fontSize }]}> 
                    {token.value}
                </Text>
            );
        }

        if (token.type === 'highlight') {
            return (
                <Text key={`${token.type}-${token.value}-${index}`} style={[styles.highlightText, { color: baseColor, fontSize }]}> 
                    {token.value}
                </Text>
            );
        }

        return (
            <Text key={`${token.type}-${token.value}-${index}`} style={{ color: baseColor, fontSize }}>
                {token.value}
            </Text>
        );
    };

    return (
        <View style={styles.genericText}>
            <Text style={[styles.contentText, { color: baseColor, fontSize }]}>
                {tokens.map(renderToken)}
            </Text>

            {expandable && isLongText && (
                <Pressable style={styles.expandButton} onPress={() => setExpanded(previous => !previous)}>
                    <Text style={styles.expandText}>{expanded ? 'Ver menos' : 'Ver mais'}</Text>
                </Pressable>
            )}
        </View>
    );
};

const parseText = (text: string, highlightTerms: string[], enableMarkdown: boolean): ParsedToken[] => {
    const tokens: ParsedToken[] = [];
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    tokenRegex.lastIndex = 0;

    while ((match = tokenRegex.exec(text)) !== null) {
        if (match.index > lastIndex) {
            pushTextWithHighlights(tokens, text.slice(lastIndex, match.index), highlightTerms);
        }

        const matched = match[0];

        if (matched.startsWith('@')) {
            tokens.push({
                type: 'mention',
                value: matched.slice(1)
            });
        } else if (matched.startsWith('#')) {
            tokens.push({
                type: 'hashtag',
                value: matched.slice(1)
            });
        } else if (matched.startsWith('http')) {
            tokens.push({
                type: 'link',
                value: matched
            });
        } else if (matched.startsWith('**') && matched.endsWith('**')) {
            tokens.push({
                type: enableMarkdown ? 'bold' : 'text',
                value: matched.replace(/\*\*/g, '')
            });
        } else if (matched.startsWith('*') && matched.endsWith('*')) {
            tokens.push({
                type: enableMarkdown ? 'italic' : 'text',
                value: matched.replace(/\*/g, '')
            });
        } else {
            tokens.push({
                type: 'emoji',
                value: matched
            });
        }

        lastIndex = tokenRegex.lastIndex;
    }

    if (lastIndex < text.length) {
        pushTextWithHighlights(tokens, text.slice(lastIndex), highlightTerms);
    }

    return tokens;
};

const pushTextWithHighlights = (tokens: ParsedToken[], text: string, highlightTerms: string[]) => {
    if (!highlightTerms.length || !text) {
        tokens.push({ type: 'text', value: text });
        return;
    }

    const escapedTerms = highlightTerms
        .filter(Boolean)
        .map(escapeRegExp);

    if (!escapedTerms.length) {
        tokens.push({ type: 'text', value: text });
        return;
    }

    const highlightRegex = new RegExp(`(${escapedTerms.join('|')})`, 'gi');
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = highlightRegex.exec(text)) !== null) {
        if (match.index > lastIndex) {
            tokens.push({ type: 'text', value: text.slice(lastIndex, match.index) });
        }

        tokens.push({ type: 'highlight', value: match[0] });
        lastIndex = highlightRegex.lastIndex;
    }

    if (lastIndex < text.length) {
        tokens.push({ type: 'text', value: text.slice(lastIndex) });
    }
};

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const styles = StyleSheet.create({
    genericText: {
        width: '100%'
    },
    contentText: {
        lineHeight: 21,
        flexWrap: 'wrap'
    },
    clickableText: {
        color: '#1881E2',
        fontWeight: '600'
    },
    linkText: {
        color: '#8ab4f8',
        fontWeight: '600'
    },
    boldText: {
        fontWeight: '700'
    },
    italicText: {
        fontStyle: 'italic'
    },
    highlightText: {
        backgroundColor: 'rgba(255, 230, 0, 0.22)',
        borderRadius: 4,
        overflow: 'hidden'
    },
    expandButton: {
        marginTop: 4,
        alignSelf: 'flex-start'
    },
    expandText: {
        color: '#8e8e8e',
        fontSize: 14,
        fontWeight: '600'
    }
});

export default GenericText;

// frontend/client/src/app/shared/components/generic-text/generic-text.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    EventEmitter,
    Input,
    OnChanges,
    Output,
    SimpleChanges
} from '@angular/core';

import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { ThemeService } from '../../../core/services/theme.service';

interface ParsedToken {
    type:
        | 'text'
        | 'mention'
        | 'hashtag'
        | 'link'
        | 'emoji'
        | 'markdown';

    value: string;

    html: string;
}

@Component({
    selector: 'app-generic-text',
    standalone: true,
    imports: [CommonModule, RouterModule],
    templateUrl: './generic-text.component.html',
    styleUrl: './generic-text.component.scss',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class GenericTextComponent implements OnChanges {

    @Input() text: string = '';

    @Input() maxCharacters: number = 180;

    @Input() expandable: boolean = true;

    @Input() theme: 'light' | 'dark' | undefined = undefined;

    @Input() textColor?: string = "none";

    @Input() clickableMentions: boolean = true;

    @Input() clickableHashtags: boolean = true;

    @Input() clickableLinks: boolean = true;

    @Input() highlightTerms: string[] = [];

    @Input() translatedText?: string;

    @Input() enableMarkdown: boolean = true;

    @Input() analyticsId?: string;

    @Output() mentionClick = new EventEmitter<string>();

    @Output() hashtagClick = new EventEmitter<string>();

    @Output() linkClick = new EventEmitter<string>();

    expanded: boolean = false;

    renderedHtml!: SafeHtml;

    private parsedTokens: ParsedToken[] = [];

    constructor(
        private readonly sanitizer: DomSanitizer,
        private readonly themeService: ThemeService
    ) { 
        if(!this.theme) this.theme = themeService.getTheme();
    }

    ngOnChanges(changes: SimpleChanges): void {
        if (
            changes['text'] ||
            changes['translatedText'] ||
            changes['highlightTerms']
        ) {
            this.parseText();
        }
    }

    get currentText(): string {

        return this.translatedText || this.text || '';
    }

    get isLongText(): boolean {

        return this.currentText.length > this.maxCharacters;
    }

    get displayedText(): string {

        if (
            !this.expandable ||
            this.expanded ||
            !this.isLongText
        ) {
            return this.currentText;
        }

        return `${this.currentText.slice(0, this.maxCharacters)}...`;
    }

    toggleExpanded(): void {

        this.expanded = !this.expanded;

        this.parseText();
    }

    handleMentionClick(value: string): void {
        this.mentionClick.emit(value);
    }

    handleHashtagClick(value: string): void {
        this.hashtagClick.emit(value);
    }

    handleLinkClick(value: string): void {
        this.linkClick.emit(value);
    }

    private parseText(): void {

        const text = this.displayedText;

        const regex =
            /(https?:\/\/[^\s]+)|(@[\p{L}0-9_\.]+)|(#[\p{L}0-9_]+)|(\*\*.*?\*\*)|(\*.*?\*)|([\u{1F300}-\u{1FAFF}])/gu;

        const tokens: ParsedToken[] = [];

        let lastIndex = 0;

        let match;

        while ((match = regex.exec(text)) !== null) {

            if (match.index > lastIndex) {

                const plainText = text.slice(lastIndex, match.index);

                tokens.push({
                    type: 'text',
                    value: plainText,
                    html: this.escapeHtml(plainText)
                });
            }

            const matched = match[0];

            if (matched.startsWith('@')) {

                const username = matched.slice(1);

                tokens.push({
                    type: 'mention',
                    value: username,
                    html: this.clickableMentions
                        ? `<a class="mention" href="/${username}" data-mention="${username}">@${username}</a>`
                        : matched
                });
            }
            else if (matched.startsWith('#')) {

                const hashtag = matched.slice(1);

                tokens.push({
                    type: 'hashtag',
                    value: hashtag,
                    html: this.clickableHashtags
                        ? `<a class="hashtag" href="/explore/topics/${hashtag}" data-hashtag="${hashtag}">#${hashtag}</a>`
                        : matched
                });
            }
            else if (matched.startsWith('http')) {

                tokens.push({
                    type: 'link',
                    value: matched,
                    html: this.clickableLinks
                        ? `<a class="link" href="${matched}" target="_blank" rel="noopener noreferrer">${matched}</a>`
                        : matched
                });
            }
            else if (
                matched.startsWith('**') &&
                matched.endsWith('**')
            ) {

                const value = matched
                    .replace(/\*\*/g, '');

                tokens.push({
                    type: 'markdown',
                    value,
                    html: this.enableMarkdown
                        ? `<strong>${value}</strong>`
                        : value
                });
            }
            else if (
                matched.startsWith('*') &&
                matched.endsWith('*')
            ) {

                const value = matched
                    .replace(/\*/g, '');

                tokens.push({
                    type: 'markdown',
                    value,
                    html: this.enableMarkdown
                        ? `<em>${value}</em>`
                        : value
                });
            }
            else {

                tokens.push({
                    type: 'emoji',
                    value: matched,
                    html: matched
                });
            }

            lastIndex = regex.lastIndex;
        }

        if (lastIndex < text.length) {

            const remaining = text.slice(lastIndex);

            tokens.push({
                type: 'text',
                value: remaining,
                html: this.escapeHtml(remaining)
            });
        }

        this.parsedTokens = tokens;

        this.renderedHtml = this.sanitizer
            .bypassSecurityTrustHtml(
                this.applyHighlights(
                    tokens.map(token => token.html).join('')
                )
            );
    }

    private applyHighlights(text: string): string {

        if (!this.highlightTerms?.length) {
            return text;
        }

        let highlighted = text;

        this.highlightTerms.forEach(term => {

            const regex = new RegExp(`(${term})`, 'gi');

            highlighted = highlighted.replace(
                regex,
                '<mark>$1</mark>'
            );
        });

        return highlighted;
    }

    private escapeHtml(text: string): string {

        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#1881E2;')
            .replace(/\n/g, '<br>');
    }
}
<div
    class="generic-text"
    [class.light]="(!textColor || textColor === 'none') && theme === 'light'"
    [class.dark]="(!textColor || textColor === 'none') && theme === 'dark'"
    [style.color]="textColor && textColor !== 'none' ? textColor : null">

    <div
        class="generic-text__content"
        [innerHTML]="renderedHtml">
    </div>

    @if(expandable && isLongText) {

        <button
            class="generic-text__expand"
            (click)="toggleExpanded()">

            {{ expanded ? 'Ver menos' : 'Ver mais' }}

        </button>
    }

</div>
